name: test
on: [ push, pull_request, workflow_dispatch ]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        perl-version: [ 34, 32, 30, 28, 26, 24, 22 ]
    container:
      image: perldocker/perl-tester:5.${{ matrix.perl-version }}
    steps:
      - uses: actions/checkout@v2
      - uses: perl-actions/install-with-cpanm@v1
        env:
          PERL_CPANM_OPT: --from https://cpan.metacpan.org/ --notest --force --skip-satisfied
        with:
          sudo: false
          args: --with-develop --with-all-features --installdeps .
      - run: HARNESS_PERL_SWITCHES=-MDevel::Cover prove --recurse --lib --failures --jobs 4 --timer t
      - run: cover -report codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        if: env.CODECOV_TOKEN != null && matrix.perl-version >= 26
