name: test
on: [ push, pull_request, workflow_dispatch ]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        perl-version: [ 38, 36, 34, 32, 30, 28, 26, 24, 22 ]
    container:
      image: perldocker/perl-tester:5.${{ matrix.perl-version }}
    steps:
      - uses: actions/checkout@v4
      - run: cpanm --with-develop --with-all-features --installdeps .
        env:
          PERL_CPANM_OPT: --from https://cpan.metacpan.org/ --notest --force --skip-satisfied
      - run: prove --recurse --lib --failures --jobs 4 --timer t
        env:
          HARNESS_PERL_SWITCHES: -MDevel::Cover
      - run: cover -report codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        if: env.CODECOV_TOKEN != null && matrix.perl-version >= 26
